### ISSUE TITLE
App Not Available on App Store

### ISSUE THREAD

**Issue by rsodre** [marcgarreau/mintclock#4]
Why would Mint Clock not be available in all regions on the App Store?
Eth is global, please remove region restrictions.

> App Not Available
> This app is currently not available in your country or region.

<img width="372" alt="Screenshot 2024-10-08 at 11 39 45" src="https://github.com/user-attachments/assets/9bc09721-d3ee-40de-8c55-96e3278c258d">

**Comment by wolovim** [comment]
it was globally available while published, but App Store took it down because ...its the App Store and dumb hoops must be jumped through occasionally. if i get time, i'll look into resubmitting the app Soon™.
